### ISSUE TITLE
@ mentioning a user causes entire message to be overloaded by color

### ISSUE THREAD

**Issue by mekasu0124** [CommandCrafterHD/DiscordDarkNeon#12]
![image](https://github.com/CommandCrafterHD/DiscordDarkNeon/assets/96821081/3a8f0eb8-8759-4051-8da6-c90edf43f6fc)

when I get mentioned in a message, the color fill effect completely drowns out the entire message. I'm not sure if this is just a visual glitch on my end, but it's there and happens.

**Comment by CommandCrafterHD** [comment]
Fixed with 6a915c3!

**Comment by mekasu0124** [comment]
> Fixed with [6a915c3](https://github.com/CommandCrafterHD/DiscordDarkNeon/commit/6a915c3f0211c1da93b4820d842f8e1f9984a4ba)!

thank you <3
